# CodeRabbit Configuration
# https://docs.coderabbit.ai/guides/review-settings

# Enable reviews for all pull requests
reviews:
  # Review pull requests from dependency update bots
  auto_review:
    enabled: true
    # Include Renovate bot commits
    drafts: false
    base_branches:
      - main
      - master

  # Enable reviews for bot-created PRs
  bot_reviews:
    enabled: true
    # Specifically allow Renovate bot
    allowed_bots:
      - "renovate[bot]"
      - "renovate-bot"

  # Review settings
  request_changes: ask
  approve: auto

# Language and framework detection
language:
  javascript: true
  typescript: true
  json: true
  yaml: true
  markdown: true

# Path-based rules
path_instructions:
  - path: "package.json"
    instructions: "Focus on dependency version changes and security implications"
  - path: "pnpm-lock.yaml"
    instructions: "Review for any unexpected dependency changes"
  - path: "renovate.json"
    instructions: "Validate Renovate configuration syntax and settings"

# Chat settings
chat:
  auto_reply: false
